name: Eleventy Build
on:
  push:
    branches:
      - source  # default branch
  pull_request:
    branches:
      - source

jobs:
  build_deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8  # v4.0.2
        with:
          node-version: '18'

      - name: Build HTML pages using eleventy
        run:
          npm install
          npm run build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          publish_dir: _site
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
