name: Eleventy Build
on:
  push:
    branches:
      - source  # default branch
  pull_request:
    branches:
      - source

jobs:
  build_deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0
        with:
          submodules: true

      - name: Build HTML pages using eleventy
        uses: TartanLlama/actions-eleventy@v1.3
        with:
          install_dependencies: true

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          publish_dir: _site
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
